kind: Service
apiVersion: v1
metadata:
  name: result-service
  labels:
     name: result-service
     app: demo-voting-app
spec:
  selector:
    name: result-app-pod
    app: demo-voting-app
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
